# Generated by Django 4.2.14 on 2024-10-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_options_alter_products_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="is_weekly_bargain",
            field=models.BooleanField(
                default=False, help_text="Mark this product as a weekly bargain"
            ),
        ),
    ]
