# Generated by Django 4.2.14 on 2024-11-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_products_is_weekly_bargain"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="has_sizes",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
